name: "Extra View Modes"
type: "View Modes"
description: 'Adds useful entity view modes (featured teaser, metro tile, slide view, etc.) used by other Extra recipes.'
install:
  - node
  - taxonomy
config:
  strict: false
